CC = gcc
shell: cd.c discover.c echo.c fb.c history.c ls.c pinfo.c pwd.c io.c shell.c 
	$(CC) shell.c cd.c discover.c echo.c fb.c history.c ls.c pinfo.c pwd.c io.c jobs.c sig.c fgbg.c signals.c pipe.c -o shell